### ISSUE TITLE
React-native support

### ISSUE THREAD

**Issue by rajibulanam** [hiukim/mind-ar-js-react#6]
Hi,
Is it possible to use this library in React-native for mobile?

**Comment by shb3014** [comment]
Same question here too.

**Comment by eddiecarbin** [comment]
I just finished using Mind-AR with ReactJS and Typescript.   The hard part of setting it up was Mind-AR dependency on AFrame.  There is a pure ThreeJs way to run mind-ar, but I found it not as well supported as the AFrame version.   This library worked the best for AFrame in ReactJS Typescript.  https://www.npmjs.com/package/types-aframe-react
